### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by MaciejCiesielsk** [MaciejCiesielsk/PyrcampApp#3]
- Learn more about firebase
- Prepare presentation for next meeting
- Optimize database

**Comment by Qu1dek** [comment]
Partly fixed, merging documents and collections within a database works,
TODO: Discuss the actual look and functionalities of the database, decide whether we join databases using UID (do we need it)
- think how "additional" persons' accounts should be created, add the functionality
- explain to Maciek what we discussed today
